<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2016-07-30 11:23:26 --> 404 Page Not Found: Faviconico/index
ERROR - 2016-07-30 11:23:27 --> 404 Page Not Found: Index/images
ERROR - 2016-07-30 11:23:38 --> Severity: Notice --> Undefined index: id F:\www\company\tianfeng\sites\user.tianfeng.com\controllers\User.php 216
ERROR - 2016-07-30 11:23:38 --> Severity: Notice --> Undefined variable: jsApiParameters F:\www\company\tianfeng\sites\user.tianfeng.com\views\pay\wx_pay.php 24
ERROR - 2016-07-30 11:23:38 --> Severity: Notice --> Undefined variable: pay_id F:\www\company\tianfeng\sites\user.tianfeng.com\views\pay\wx_pay.php 29
ERROR - 2016-07-30 11:23:38 --> Severity: Notice --> Undefined variable: pay_id F:\www\company\tianfeng\sites\user.tianfeng.com\views\pay\wx_pay.php 31
ERROR - 2016-07-30 11:23:38 --> Severity: Notice --> Undefined variable: pay_money F:\www\company\tianfeng\sites\user.tianfeng.com\views\pay\wx_pay.php 65
ERROR - 2016-07-30 13:44:10 --> Severity: Notice --> Undefined index: id F:\www\company\tianfeng\sites\user.tianfeng.com\controllers\User.php 218
ERROR - 2016-07-30 13:44:10 --> 404 Page Not Found: Img/common
ERROR - 2016-07-30 13:44:22 --> Severity: Notice --> Undefined index: id F:\www\company\tianfeng\sites\user.tianfeng.com\controllers\User.php 218
ERROR - 2016-07-30 13:44:22 --> 404 Page Not Found: Img/common
ERROR - 2016-07-30 13:45:58 --> Severity: Notice --> Undefined index: id F:\www\company\tianfeng\sites\user.tianfeng.com\controllers\User.php 218
ERROR - 2016-07-30 13:46:07 --> Severity: Notice --> Undefined index: id F:\www\company\tianfeng\sites\user.tianfeng.com\controllers\User.php 218
ERROR - 2016-07-30 13:46:12 --> Severity: Notice --> Undefined index: id F:\www\company\tianfeng\sites\user.tianfeng.com\controllers\User.php 218
ERROR - 2016-07-30 13:46:49 --> Severity: Notice --> Undefined index: id F:\www\company\tianfeng\sites\user.tianfeng.com\controllers\User.php 218
ERROR - 2016-07-30 13:48:10 --> Severity: Notice --> Undefined index: id F:\www\company\tianfeng\sites\user.tianfeng.com\controllers\User.php 218
ERROR - 2016-07-30 13:48:56 --> Severity: Notice --> Undefined index: levle F:\www\company\tianfeng\sites\user.tianfeng.com\views\pay\pay_success.php 27
ERROR - 2016-07-30 13:50:16 --> Severity: Notice --> Undefined index: levle F:\www\company\tianfeng\sites\user.tianfeng.com\views\pay\pay_success.php 27
ERROR - 2016-07-30 13:50:38 --> Severity: Notice --> Undefined index: levle F:\www\company\tianfeng\sites\user.tianfeng.com\views\pay\pay_success.php 27
ERROR - 2016-07-30 13:55:54 --> Severity: Notice --> Undefined index: levle F:\www\company\tianfeng\sites\user.tianfeng.com\views\pay\pay_success.php 27
ERROR - 2016-07-30 14:01:02 --> Severity: error --> Exception: Call to undefined function I() F:\www\company\tianfeng\sites\user.tianfeng.com\views\pay\pay_success.php 24
ERROR - 2016-07-30 14:01:02 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php on line 658 and defined in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php:190
Stack trace:
#0 F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php 190
ERROR - 2016-07-30 14:01:02 --> 404 Page Not Found: Img/common
ERROR - 2016-07-30 14:01:03 --> Severity: error --> Exception: Call to undefined function I() F:\www\company\tianfeng\sites\user.tianfeng.com\views\pay\pay_success.php 24
ERROR - 2016-07-30 14:01:03 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php on line 658 and defined in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php:190
Stack trace:
#0 F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php 190
ERROR - 2016-07-30 14:01:03 --> 404 Page Not Found: Img/common
ERROR - 2016-07-30 14:01:10 --> 404 Page Not Found: Img/common
ERROR - 2016-07-30 14:01:11 --> 404 Page Not Found: Img/common
ERROR - 2016-07-30 14:01:19 --> 404 Page Not Found: Img/common
ERROR - 2016-07-30 14:01:28 --> Severity: Notice --> Undefined index: levle F:\www\company\tianfeng\sites\user.tianfeng.com\views\pay\pay_success.php 26
ERROR - 2016-07-30 14:01:31 --> Severity: Notice --> Undefined index: levle F:\www\company\tianfeng\sites\user.tianfeng.com\views\pay\pay_success.php 26
ERROR - 2016-07-30 14:08:52 --> 404 Page Not Found: User/%E8%AE%A2%E5%8D%95%E6%94%AF%E4%BB%98%E6%88%90%E5%8A%9F-%E5%85%A8%E5%B1%8B%E4%BC%98%E5%93%81_files
ERROR - 2016-07-30 14:08:52 --> 404 Page Not Found: User/%E8%AE%A2%E5%8D%95%E6%94%AF%E4%BB%98%E6%88%90%E5%8A%9F-%E5%85%A8%E5%B1%8B%E4%BC%98%E5%93%81_files
ERROR - 2016-07-30 14:08:53 --> 404 Page Not Found: User/%E8%AE%A2%E5%8D%95%E6%94%AF%E4%BB%98%E6%88%90%E5%8A%9F-%E5%85%A8%E5%B1%8B%E4%BC%98%E5%93%81_files
ERROR - 2016-07-30 14:16:15 --> 404 Page Not Found: User/%E8%AE%A2%E5%8D%95%E6%94%AF%E4%BB%98%E6%88%90%E5%8A%9F-%E5%85%A8%E5%B1%8B%E4%BC%98%E5%93%81_files
ERROR - 2016-07-30 14:16:15 --> 404 Page Not Found: User/%E8%AE%A2%E5%8D%95%E6%94%AF%E4%BB%98%E6%88%90%E5%8A%9F-%E5%85%A8%E5%B1%8B%E4%BC%98%E5%93%81_files
ERROR - 2016-07-30 14:16:16 --> 404 Page Not Found: User/%E8%AE%A2%E5%8D%95%E6%94%AF%E4%BB%98%E6%88%90%E5%8A%9F-%E5%85%A8%E5%B1%8B%E4%BC%98%E5%93%81_files
ERROR - 2016-07-30 14:17:10 --> 404 Page Not Found: User/%E8%AE%A2%E5%8D%95%E6%94%AF%E4%BB%98%E6%88%90%E5%8A%9F-%E5%85%A8%E5%B1%8B%E4%BC%98%E5%93%81_files
ERROR - 2016-07-30 14:17:10 --> 404 Page Not Found: Img/common
ERROR - 2016-07-30 14:17:11 --> 404 Page Not Found: User/%E8%AE%A2%E5%8D%95%E6%94%AF%E4%BB%98%E6%88%90%E5%8A%9F-%E5%85%A8%E5%B1%8B%E4%BC%98%E5%93%81_files
ERROR - 2016-07-30 14:17:11 --> 404 Page Not Found: Img/common
ERROR - 2016-07-30 14:19:56 --> 404 Page Not Found: User/%E8%AE%A2%E5%8D%95%E6%94%AF%E4%BB%98%E6%88%90%E5%8A%9F-%E5%85%A8%E5%B1%8B%E4%BC%98%E5%93%81_files
ERROR - 2016-07-30 14:23:39 --> Severity: Notice --> Undefined index: levle F:\www\company\tianfeng\sites\user.tianfeng.com\views\pay\pay_success.php 43
ERROR - 2016-07-30 15:06:17 --> 404 Page Not Found: Img/common
ERROR - 2016-07-30 15:06:17 --> 404 Page Not Found: Img/common
ERROR - 2016-07-30 15:06:18 --> 404 Page Not Found: Img/common
ERROR - 2016-07-30 15:06:18 --> 404 Page Not Found: Img/common
ERROR - 2016-07-30 17:32:00 --> Severity: error --> Exception: Call to undefined function XmlToArray() F:\www\company\tianfeng\sites\user.tianfeng.com\controllers\Api.php 50
ERROR - 2016-07-30 17:32:00 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php on line 658 and defined in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php:190
Stack trace:
#0 F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php 190
ERROR - 2016-07-30 17:32:35 --> Severity: error --> Exception: Call to undefined function XmlToArray() F:\www\company\tianfeng\sites\user.tianfeng.com\controllers\Api.php 50
ERROR - 2016-07-30 17:32:35 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php on line 658 and defined in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php:190
Stack trace:
#0 F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php 190
ERROR - 2016-07-30 17:32:35 --> Severity: error --> Exception: Call to undefined function XmlToArray() F:\www\company\tianfeng\sites\user.tianfeng.com\controllers\Api.php 50
ERROR - 2016-07-30 17:32:35 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php on line 658 and defined in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php:190
Stack trace:
#0 F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php 190
ERROR - 2016-07-30 17:32:50 --> Severity: error --> Exception: Call to undefined function XmlToArray() F:\www\company\tianfeng\sites\user.tianfeng.com\controllers\Api.php 50
ERROR - 2016-07-30 17:32:50 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php on line 658 and defined in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php:190
Stack trace:
#0 F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php 190
ERROR - 2016-07-30 17:33:35 --> Severity: error --> Exception: Class 'WxPayException' not found F:\www\company\tianfeng\sites\common\helpers\core_helper.php 230
ERROR - 2016-07-30 17:33:35 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php on line 658 and defined in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php:190
Stack trace:
#0 F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php 190
ERROR - 2016-07-30 17:33:36 --> Severity: error --> Exception: Class 'WxPayException' not found F:\www\company\tianfeng\sites\common\helpers\core_helper.php 230
ERROR - 2016-07-30 17:33:36 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php on line 658 and defined in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php:190
Stack trace:
#0 F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php 190
ERROR - 2016-07-30 17:33:37 --> Severity: error --> Exception: Class 'WxPayException' not found F:\www\company\tianfeng\sites\common\helpers\core_helper.php 230
ERROR - 2016-07-30 17:33:37 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php on line 658 and defined in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php:190
Stack trace:
#0 F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php 190
ERROR - 2016-07-30 17:34:46 --> Severity: error --> Exception: Class 'WxPayException' not found F:\www\company\tianfeng\sites\common\helpers\core_helper.php 230
ERROR - 2016-07-30 17:34:46 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php on line 658 and defined in F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php:190
Stack trace:
#0 F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown F:\www\company\tianfeng\libs\Codeigniter\3.0.0\core\Exceptions.php 190
